### ISSUE TITLE
Cannot install on Mac Sierra

### ISSUE THREAD

**Issue by jbone** [witheve/eve-starter#6]
Transcript:

:; mkdir eve

:; cd !$
cd eve
/Users/jbone/Src/projects/kiddos/eve

:; c

:; node -v
v6.10.2

:; npm -v
4.2.0

:; git clone https://github.com/witheve/eve-starter.git
Cloning into 'eve-starter'...
remote: Counting objects: 266, done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 266 (delta 154), reused 266 (delta 154), pack-reused 0
Receiving objects: 100% (266/266), 282.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (154/154), done.

:; cd eve-starter/
/Users/jbone/Src/projects/kiddos/eve/eve-starter

:; ls
LICENSE		assets/		package.json	src/
README.md	index.html	programs/	tsconfig.json

:; npm install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> witheve@0.3.0-preview1 postinstall /Users/jbone/Src/projects/kiddos/eve/eve-starter/node_modules/witheve
> tsc

> witheve-starter@0.1.0 postinstall /Users/jbone/Src/projects/kiddos/eve/eve-starter
> tsc

src/cli.ts(55,19): error TS2345: Argument of type '{ workspacePaths: string; watcherPaths: string; watch: string; port: string; open: string; }' is not assignable to parameter of type 'Partial<Config>'.
  Types of property 'workspacePaths' are incompatible.
    Type 'string' is not assignable to type '{ [workspaceId: string]: string; } | undefined'.

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.2
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! witheve-starter@0.1.0 postinstall: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the witheve-starter@0.1.0 postinstall script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the witheve-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs witheve-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls witheve-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jbone/.npm/_logs/2017-04-17T18_16_02_124Z-debug.log

:; 

LOG:

https://gist.github.com/jbone/0caeed296d542bedd1351677807ad1c5

Thoughts?

jb

**Comment by joshuafcole** [comment]
Hey @jbone 

Good catch, thanks for bringing this to our attention. Unfortunately either typescript pushed a change to type checking (making it stricter) or the typings we use for Commander JS pushed a breaking (and incorrect) change marking all options as strings. In either case, it's not really an error and has been hinted as such in: https://github.com/witheve/eve-starter/commit/40c0742da1d6bb79ec4591a621ecc3509454facc . Additionally, I've locked the typescript version to only patch update without manual intervention.

This should be fixed in master, if you have any further issues please let us know!
